# Setup
title:               YON
tagline:             CISE
description:         "I'm the type of person that if you ask me a question and I don't know the answer, I'm gonna tell you that I don't know. But I bet you what, I know how to find the answer and I will find the answer."
url:                 https://yoncise.com
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              YAO YUAN
  email:             yoncise@gmail.com

defaults:
  -
    scope:
      path: "logs"
      type: "posts"
    values:
      hidden: true

# Gems
plugins:
  - jekyll-paginate
